[project]
name = "cloudflare-new-email"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
]
